repos:
  # General formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm/.*\.yaml$
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=10240"] # 10MB limit
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      # Temporarily disabled for initial setup
      # - id: no-commit-to-branch
      #   args: ['--branch', 'main', '--branch', 'master']

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-e", "SC1091"] # Disable sourcing errors for dynamic paths

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  # Kubernetes and Helm linting
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint

  # Docker linting
  - repo: https://github.com/hadolint/hadolint # pragma: allowlist secret
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore", "DL3008", "--ignore", "DL3009"]

  # Markdown linting and formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli # pragma: allowlist secret
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  # Terraform (if used)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, json]
        exclude: |
          (?x)^(
              helm/.*\.yaml$|
              helm/.*values.*\.yaml|
              .*Chart\.yaml|
              .*chart/templates/.*\.yaml
          )$

  # Custom local hooks
  - repo: local
    hooks:
      - id: kubernetes-secrets-check
        name: Check for hardcoded secrets in Kubernetes manifests
        entry: scripts/check-k8s-secrets.sh
        language: script
        files: '.*\.(yaml|yml)$'
        exclude: '^(\.pre-commit-config\.yaml|helm/.*values.*\.yaml)$'

      - id: dockerfile-best-practices
        name: Check Dockerfile best practices
        entry: scripts/check-dockerfile.sh
        language: script
        files: "Dockerfile.*"
